name: 2GP Feature Test

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
      gh-email:
        required: true      
      github-token:
        required: true

jobs:
    feature-test:
        name: "Feature Test"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/muselab-d2x/d2x:latest
            options: --user root
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github-token }}
            env:
                DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
                CUMULUSCI_SERVICE_github: "{ \"username\": \"${{ github.actor }}\", \"token\": \"${{ secrets.github-token }}\", \"email\": \"${{ secrets.gh-email }}\" }"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Auth to DevHub
              run: /usr/local/bin/devhub.sh
            - name: Set feature org as default org
              run: cci org default feature
            - name: Run Feature Test
              run: cci flow run ci_feature
            - name: Delete Scratch Org
              if: ${{ always() }}
              run: |
                cci org scratch_delete dev
              shell: bash