name: Static Analysis

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: false
      dev-hub-username:
        required: false
      dev-hub-client-id:
        required: false
      dev-hub-private-key:
        required: false
      gh-email:
        required: true
      github-token:
        required: true
      pkg-ver-auth:
        required: true
      pkg-ver-url:
        required: true

jobs:
  analyze:
    name: "Static Analysis Run"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearrisk/d2x:latest
      options: --user root
      credentials:
        username: "${{ github.actor }}"
        password: "${{ secrets.github-token }}"
      env:
        DEV_HUB_AUTH_URL: "${{ secrets.dev-hub-auth-url }}"
        DEV_HUB_USERNAME: "${{ secrets.dev-hub-username }}"
        DEV_HUB_CLIENT_ID: "${{ secrets.dev-hub-client-id }}"
        DEV_HUB_PRIVATE_KEY: "${{ secrets.dev-hub-private-key }}"
        CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: masterRuleset.xml
          severity-threshold: 4
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
